from enum import Enum, auto


class SpellType(Enum):
    NONE = auto()
    REVELIO = auto()
    LOCOMOTOR = auto()
    ARRESTO_MOMENTUM = auto()
    WINGARDIIUM_LEVIOSA = auto()
    METEOLOJINX = auto()
    COLOVARIA = auto()
    SLUGULUS_ERECTO = auto()
    VENTUS = auto()
    RICTUSEMPRA = auto()
    REPARO = auto()
    PIERTOTUM_LOCOMOTOR = auto()
    ALOHOMORA = auto()
    COLLOPORTUS = auto()
    SILENCIO = auto()
    INCENDIO = auto()
    INFLATUS = auto()
    IMMOBULUS = auto()
    APARECIUM = auto()
    ENGORGIO = auto()
    SQITCHING = auto()
    CANTIS = auto()
    PEPPER_BREATH = auto()
    VERA_VERTO = auto()
    DENSAUGEO = auto()
    HORN_TONGUE = auto()
    FLIPENDO = auto()
    EXPECTO_PATRONUM = auto()
    LUMOS_MAXIMA = auto()
    HERBIVICIUS = auto()
    NEBULUS = auto()
