from collections.abc import Callable

from input.wand_position import WandPosition


class VisualiserProtocol:
    def start(self) -> None: ...

    def stop(self) -> None: ...

    def update(self) -> None: ...

    def clear(self) -> None: ...

    def register_key_callback(self, key: str, callback: Callable[[], None]) -> None: ...

    def unregister_key_callbacks(self, key: str) -> None: ...

    def add_position(self, wand_position: WandPosition) -> None: ...
