from collections.abc import Callable

from gamevolt.events.event import Event
from spells.scoring.cast_attempt import CastAttempt
from wand.wand_rotation import WandRotation


class WandVisualiserProtocol:
    def start(self) -> None: ...

    def stop(self) -> None: ...

    def update(self) -> None: ...

    def clear(self) -> None: ...

    def register_key_callback(self, key: str, callback: Callable[[], None]) -> None: ...

    def unregister_key_callbacks(self, key: str) -> None: ...

    def add_rotation(self, wand_position: WandRotation) -> None: ...

    def reset_trail(self, wand_id: str) -> None: ...

    def show_cast_attempt(self, attempt: CastAttempt) -> None: ...

    # Zone presence hooks. Wired from the zone manager by the builder; the multi-wand
    # RTLS visualiser uses them to add/remove a wand's trail + legend row. No-ops by
    # default so single-wand / headless visualisers ignore them.
    def wand_entered_zone(self, wand_id: str, zone_id: str, spell_labels: list[str]) -> None: ...

    def wand_exited_zone(self, wand_id: str) -> None: ...

    # Battery telemetry hook. Wired from the battery monitor by the builder on the
    # single-anchor path; no-op by default so other visualisers ignore it.
    def set_wand_battery(self, wand_id: str, millivolts: int, percent: float) -> None: ...

    # Silent IMU stall flag (PR quiet, GDHR answering). Wired from the stall
    # detector by the builder on the single-anchor path; no-op by default.
    def set_wand_imu_stalled(self, wand_id: str, stalled: bool) -> None: ...

    @property
    def quit(self) -> Event[Callable[[], None]]: ...

    @property
    def reset_xp_requested(self) -> Event[Callable[[], None]]: ...

    @property
    def record_session_changed(self) -> Event[Callable[[bool, str], None]]: ...
